export default [{
  created_at: 'Mon Nov 20 09:52:43 +0000 2017',
  id: 932547242002735100,
  id_str: '932547242002735104',
  text: 'Lorem ipsum dolores amen. Lorem ipsum dolores amen. Lorem ipsum dolores amen. Lorem ipsum dolores amen. Lorem ipsum dolores amen. Lorem ipsum dolores amen.',
  truncated: false,
  entities: {
    hashtags: [],
    symbols: [{
      text: 'PAY',
      indices: [15, 19],
    }],
    user_mentions: [{
      screen_name: 'BlockerNL',
      name: 'Blocker.nl',
      id: 876191378031751200,
      id_str: '876191378031751168',
      indices: [3, 13],
    }],
    urls: [],
  },
  metadata: {
    iso_language_code: 'nl',
    result_type: 'rec e nt',
  },
  source: '<a href="http://twitte r .com/downl o ad/iphone" rel="nofol l ow">Twitter for iPhone</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 4822034967,
    id_str: '4822034967',
    name: 'BlauwBloedClash',
    screen_name: 'BlauwBloedClash',
    location: 'Rijswijk, Zuid-Holland',
    description: 'Clubhuis van BlauwBloed - we heten iedereen welkom die ook van Clash houdt! Sub op Youtube en mis niets...',
    url: 'https://t.co/Dkqg8UQiMU',
    entities: {
      url: {
        urls: [{
          url: 'https://t.co/Dkqg8UQiMU',
          expanded_url: 'http://Www.youtube.com/BlauwBloedClash',
          display_url: 'youtube.com/BlauwBloedClash',
          indices: [0, 23],
        }],
      },
      description: {
        urls: [],
      },
    },
    protected: false,
    followers_count: 152,
    friends_count: 4,
    listed_count: 0,
    created_at: 'Sun Jan 17 20:27:42 +0000 2016',
    favourites_count: 866,
    utc_offset: null,
    time_zone: null,
    geo_enabled: true,
    verified: false,
    statuses_count: 235,
    lang: 'nl',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'F5F8FA',
    profile_background_image_url: null,
    profile_background_image_url_https: null,
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/693409924185985024/zk3m2yk8_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/693409924185985024/zk3m2yk8_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/4822034967/1453579048',
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: true,
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    translator_type: 'none',
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweeted_status: {
    created_at: 'Mon Nov 20 08:30:41 +0000 2017',
    id: 932526599609647100,
    id_str: '932526599609647104',
    text: '$PAY haalde ooit $67miljoen (!) op in 10 minuten, maar het aandeel heeft het lastig gehad. Toch is er rust op de US… https://t.co/i55zVuSG9k',
    truncated: true,
    entities: {
      hashtags: [],
      symbols: [{
        text: 'PAY',
        indices: [0, 4],
      }],
      user_mentions: [],
      urls: [{
        url: 'https://t.co/i55zVuSG9k',
        expanded_url: 'https://twitter.com/i/web/status/932526599609647104',
        display_url: 'twitter.com/i/web/status/9…',
        indices: [117, 140],
      }],
    },
    metadata: {
      iso_language_code: 'nl',
      result_type: 'recent',
    },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 876191378031751200,
      id_str: '876191378031751168',
      name: 'Blocker.nl',
      screen_name: 'BlockerNL',
      location: 'Nederland',
      description: 'Dé crypto- en blockchain community van de Benelux. Slack, meet-ups, (bedrijfs)trainingen en veel meer. Blockchain en crypto begint bij https://t.co/cGUKg3tFG9!',
      url: 'https://t.co/cGUKg3tFG9',
      entities: {
        url: {
          urls: [{
            url: 'https://t.co/cGUKg3tFG9',
            expanded_url: 'http://www.blocker.nl',
            display_url: 'blocker.nl',
            indices: [0, 23],
          }],
        },
        description: {
          urls: [{
            url: 'https://t.co/cGUKg3tFG9',
            expanded_url: 'http://www.blocker.nl',
            display_url: 'blocker.nl',
            indices: [135, 158],
          }],
        },
      },
      protected: false,
      followers_count: 919,
      friends_count: 58,
      listed_count: 9,
      created_at: 'Sat Jun 17 21:34:38 +0000 2017',
      favourites_count: 238,
      utc_offset: -28800,
      time_zone: 'Pacific Time (US & Canada)',
      geo_enabled: false,
      verified: false,
      statuses_count: 657,
      lang: 'nl',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/883267889620537344/xLCFpu_r_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/883267889620537344/xLCFpu_r_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/876191378031751168/1510407699',
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      has_extended_profile: false,
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: 'none',
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 7,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'nl',
  },
  is_quote_status: false,
  retweet_count: 1,
  favorite_count: 0,
  favorited: false,
  retweeted: false,
  lang: 'nl',
},
];
